name: msix
description: A command-line tool that create Msix installer from your flutter windows-build files.
version: 4.0.0
maintainer: Yehuda Kremer (yehudakremer@gmail.com)
homepage: https://github.com/YehudaKremer/msix

environment:
  sdk: ">=2.12.0 <3.0.0"

platforms:
  windows:

dependencies:
  args: ^2.3.1
  yaml: ^3.1.1
  package_config: ^2.1.0
  pub_semver: ^2.1.2
  get_it: ^7.2.0
  cli_util: ^0.3.5
  console: ^4.1.0
  path: ^1.8.2
  image: ^3.2.2

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.22.0
